=== Durvijay/IMCS_Workspace/IMCSWorkspace/MyXMLProject/target/classes/xsd/employee.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://trng.imcs.xsd/employee"
	elementFormDefault="qualified" xmlns="http://www.w3.org/2001/XMLSchema"
	xmlns:tns="http://trng.imcs.xsd/employee" xmlns:pref="http://trng.imcs.xsd/Department">

	<import schemaLocation="Department.xsd" namespace="http://trng.imcs.xsd/Department"></import>
	<complexType name="Employee">
		<sequence>
			<element name="empId" type="int" maxOccurs="1"
				minOccurs="1">
			</element>
			<element name="name" type="string"></element>
			<element name="salary">
				<simpleType>
					<restriction base="float">
						<minInclusive value="5000"></minInclusive>
					</restriction>
				</simpleType>
			</element>
			<element name="joinDate" type="date" maxOccurs="1"
				minOccurs="0">
			</element>
			<element name="phoneNumbers" type="string"
				maxOccurs="unbounded" minOccurs="1">
			</element>
			<element name="address" type="tns:Address"></element>
			<element name="empType">
				<simpleType>
					<restriction base="string">
						<enumeration value="Senior"></enumeration>
						<enumeration value="Junior"></enumeration>
					</restriction>
				</simpleType>
			</element>
			<element name="department" type="pref:Department"></element>
		</sequence>
	</complexType>

	<complexType name="Address">
		<sequence>
			<element name="streetNo" type="string"></element>
			<element name="streetName" type="string"></element>
			<element name="zipCode" type="string"></element>
		</sequence>
	</complexType>

	<element name="Employee" type="tns:Employee"></element>
</schema>

=== Durvijay/IMCS_Workspace/IMCSWorkspace/MyXMLProject/target/classes/xml/Employee.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Employee xmlns:tns="http://trng.imcs.xsd/employee" 
xmlns:tns1="http://trng.imcs.xsd/Department" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="http://trng.imcs.xsd/employee ../xsd/employee.xsd ">
  <tns:empId>12345</tns:empId>
  <tns:name>Raju</tns:name>
  <tns:salary>5000</tns:salary>
  <tns:phoneNumbers>tns:phoneNumbers</tns:phoneNumbers>
  <tns:address>
    <tns:streetNo>1234</tns:streetNo>
    <tns:streetName>MacArthur</tns:streetName>
    <tns:zipCode>45454</tns:zipCode>
  </tns:address>
  <tns:empType>Senior</tns:empType>
  <tns:department>
    <tns1:deprtNo>10</tns1:deprtNo>
    <tns1:name>Sales</tns1:name>
    <tns1:location>Dallas</tns1:location>
  </tns:department>
</tns:Employee>
